# Generated by Django 5.0.6 on 2024-07-12 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permanence',
            old_name='name',
            new_name='nom',
        ),
    ]
