# Generated by Django 5.0.3 on 2024-07-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cadre_id_alter_permanence_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permanence',
            name='nombre_cadre',
            field=models.IntegerField(null=True),
        ),
    ]
