# Generated by Django 5.0.6 on 2024-07-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_cadre_id_alter_permanence_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadre',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
