# Generated by Django 5.0.3 on 2024-07-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_permanence_nombre_cadre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permanence',
            name='nombre_cadre',
            field=models.IntegerField(default=0),
        ),
    ]
