# Generated by Django 5.0.6 on 2024-07-15 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cadre_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Affection',
            new_name='Affectation',
        ),
    ]
