# Generated by Django 5.0.6 on 2024-07-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_affection_affectation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permanence',
            name='nombre_cadre',
            field=models.IntegerField(default=0),
        ),
    ]
