# Generated by Django 5.0.6 on 2024-07-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_permanence_nombre_cadre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affectation',
            old_name='premanence',
            new_name='permanence',
        ),
    ]
