# Generated by Django 5.1 on 2024-08-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_permanence_nombre_cadre'),
        ('main', '0007_rename_premanence_affectation_permanence'),
    ]

    operations = [
    ]
