# Generated by Django 5.1 on 2024-09-19 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_merge_20240820_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('corpse', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='affectation',
            name='cadre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.cadre'),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='permanence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.permanence'),
        ),
    ]
