# Generated by Django 5.1 on 2024-09-19 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_email_alter_affectation_cadre_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='Mail',
        ),
        migrations.RenameField(
            model_name='mail',
            old_name='titre',
            new_name='objet',
        ),
    ]
